# Generated by Django 2.1.4 on 2019-02-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('collection', models.CharField(choices=[('', 'Selecione a coleção')], max_length=30, verbose_name='Handle da coleção')),
                ('dspace_simple_archive', models.FileField(upload_to='import', verbose_name='Arquivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de importação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
