# Generated by Django 2.2.13 on 2023-08-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='fileimport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Importação', 'verbose_name_plural': 'Importações'},
        ),
    ]
