# Generated by Django 2.1.7 on 2019-02-25 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20190225_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
