# Generated by Django 2.1.7 on 2019-02-26 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20190225_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('handle', models.CharField(max_length=30, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fileimport',
            name='dspace_simple_archive',
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.Collection', verbose_name='Coleção de destino'),
        ),
    ]
