# Generated by Django 5.1.3 on 2024-12-04 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPermissionUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('netid', models.CharField(max_length=255, verbose_name='Login LDAP')),
                ('created', models.BooleanField(default=False, verbose_name='Usuário criado no DSpace')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='Retorno da API')),
            ],
            options={
                'verbose_name': 'Registro de permissionamento',
                'verbose_name_plural': 'Registros de permissionamento',
            },
        ),
    ]
